n = int(input())
print(' '.join([' @@@   @@@ ' for _ in range(n)]))
print(' '.join(['@   @ @   @' for _ in range(n)]))
print(' '.join(['@    @    @' for _ in range(n)]))
print(' '.join(['@         @' for _ in range(n)]))
print(' '.join([' @       @ ' for _ in range(n)]))
print(' '.join(['  @     @  ' for _ in range(n)]))
print(' '.join(['   @   @   ' for _ in range(n)]))
print(' '.join(['    @ @    ' for _ in range(n)]))
print(' '.join(['     @     ' for _ in range(n)]))